# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
    - checkout
    # code is checked out
    - run:
        name: "Fast Config.pm"
        command: "sh contrib/install.sh"
    - run:
        name: "install UNIVERSAL::moniker"
        command: "sudo perl -MCPAN -e 'install UNIVERSAL::moniker'"
    - run:
        name: "install Module::Pluggable"
        command: "sudo perl -MCPAN -e 'install Module::Pluggable'"
    - run:
        name: "install DBI"
        command: "sudo perl -MCPAN -e 'install DBI'"
    - run:
        name: "install Ima::DBI"
        command: "sudo perl -MCPAN -e 'install Ima::DBI'"
    - run:
        name: "install Class::Accessor"
        command: "sudo perl -MCPAN -e 'install Class::Accessor'"
    - run:
        name: "install Class::DBI"
        command: "sudo perl -MCPAN -e 'install Class::DBI'"
    - run:
        name: "install Class::DBI::SQLite"
        command: "sudo perl -MCPAN -e 'install Class::DBI::SQLite'"
    - run:
        name: "Makefile.PL"
        command: "perl Makefile.PL"
    - run:
        name: "make"
        command: "make"
    - run:
        name: "test"
        command: "make test"

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test